//auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const CLEAR_LOGIN_ERROR="CLEAR_LOGIN_ERROR";
export const LOGOUT="LOGOUT";

export const GET_USER_ERROR = "GET_USER_ERROR";
export const ASSIGN_ROLE = "ASSIGN_ROLE";

//create user
export const CREATE_USER_SUCCESS="CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR="CREATE_USER_ERROR";

//dashboard
export const SIDE_BAR="SIDE_BAR";
//all users
export const GET_ALL_USERS="GET_ALL_USERS";
export const GET_ALL_USERS_ERRORS="GET_ALL_USERS_ERRORS";
export const CLEAR_GET_ALL_USERS="CLEAR_GET_ALL_USERS"
//suppliers
export const CREATE_SUPPLIER_SUCCESS="CREATE_SUPPLIER_SUCCESS";
export const CREATE_SUPPLIER_ERROR="CREATE_SUPPLIER_ERROR";
export const GET_ALL_SUPPLIERS="GET_ALL_SUPPLIERS";
export const GET_ALL_SUPPLIERS_ERROR="GET_ALL_SUPPLIERS_ERROR";
export const CLEAR_GET_ALL_SUPPLIERS="CLEAR_GET_ALL_SUPPLIERS"
//brands
export const CREATE_BRAND_SUCCESS="CREATE_BRAND_SUCCESS";
export const CREATE_BRAND_ERROR="CREATE_BRAND_ERROR";
export const GET_ALL_BRANDS="GET_ALL_BRANDS";
export const GET_ALL_BRANDS_ERROR="GET_ALL_BRANDS_ERROR";
export const CLEAR_GET_ALL_BIKES="CLEAR_GET_ALL_BIKES"

//body_types
export const CREATE_BODY_TYPE_SUCCESS="CREATE_BODY_TYPE_SUCCESS";
export const CREATE_BODY_TYPE_ERROR="CREATE_BODY_TYPE_ERROR";
export const GET_ALL_BODY_TYPES="GET_ALL_BODY_TYPES";
export const GET_ALL_BODY_TYPES_ERROR="GET_ALL_BODY_TYPES_ERROR";

//models
export const CREATE_MODEL_SUCCESS="CREATE_MODEL_SUCCESS";
export const CREATE_MODEL_ERROR="CREATE_MODEL_ERROR";
export const GET_ALL_MODELS="GET_ALL_MODELS";
export const GET_ALL_MODELS_ERROR="GET_ALL_MODELS_ERROR";

//products
export const CLEAR_GET_ALL_PRODUCTS="CLEAR_GET_ALL_PRODUCTS"
export const CREATE_PRODUCT_SUCCESS="CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_ERROR="CREATE_PRODUCT_ERROR";
export const GET_ALL_PRODUCT="GET_ALL_PRODUCT";
export const GET_ALL_PRODUCT_ERROR="GET_ALL_PRODUCT_ERROR";

//product category
export const CREATE_PRODUCT_CAT_SUCCESS="CREATE_PRODUCT_CAT_SUCCESS";
export const CREATE_PRODUCT_CAT_ERROR="CREATE_PRODUCT_CAT_ERROR";
export const GET_ALL_PRODUCT_CAT="GET_ALL_PRODUCT_CAT";
export const GET_ALL_PRODUCT_CAT_ERROR="GET_ALL_PRODUCT_CAT_ERROR";

//product subcategory
export const CREATE_PRODUCT_SUB_CAT_SUCCESS="CREATE_PRODUCT_SUB_CAT_SUCCESS";
export const CREATE_PRODUCT_SUB_CAT_ERROR="CREATE_PRODUCT_SUB_CAT_ERROR";
export const GET_ALL_PRODUCT_SUB_CAT="GET_ALL_PRODUCT_SUB_CAT";
export const GET_ALL_PRODUCT_SUB_CAT_ERROR="GET_ALL_PRODUCT_SUB_CAT_ERROR";

//product supplies
export const CREATE_SUPPLIES_SUCCESS="CREATE_SUPPLIES_SUCCESS";
export const CREATE_SUPPLIES_ERROR="CREATE_SUPPLIES_ERROR";
export const GET_ALL_SUPPLIES="GET_ALL_SUPPLIES";
export const GET_ALL_SUPPLIES_ERROR="GET_ALL_SUPPLIES_ERROR";
export const CLEAR_ALL_SUPPLIES_ERROR="CLEAR_ALL_SUPPLIES_ERROR"

//store
export const GET_ALL_PRODUCTSIN_STORE="GET_ALL_PRODUCTSIN_STORE";
export const GET_ALL_PRODUCTSIN_STORE_ERROR="GET_ALL_PRODUCTSIN_STORE_ERROR";
export const CLEAR_ALL_PRODUCTSIN_STORE_ERROR="CLEAR_ALL_PRODUCTSIN_STORE_ERROR"

//store
export const ADD_TO_CART="ADD_TO_CART";
export const CLEAR_CART="CLEAR_CART";
